### ISSUE TITLE
roadmap meta-issue

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#503]
0.4.x
- [x] probably one more release on this series

0.5.0

Feature-equivalent with the last 0.4.x release, but reorganized for ✨ THE FUTURE ✨

- [x] yax-free, with cats, as announced [here](https://http4s.github.io/fp-ecosystem/). Clean up whitespace issues and weird import renames.
- [x] interpreter into `cats.effect.IO`, which should supplant `fs2.Task`
- [x] get rid of `Catchable` and `Suspendable` (no choice really, they go away with `cats.effect`).
- [x] doc with [sbt-microsites](https://47deg.github.io/sbt-microsites/). This means we will only have published doc for the most recent version. That's good enough, we want to encourage people to keep up. If they want to look at old doc they can build it themselves.
- [ ] add `CONTRIBUTORS.md` now that the code is Scala again.

0.5.x infrastructure

- [ ] set up [sbt-rig](https://github.com/Verizon/sbt-rig) for continuous deployment

0.5.x features

- [ ] distinct thread pool for primitive ops, to take advantage of idle connections (easy to implement but hard to test … maybe add a real benchmark project w/ slick, etc., for comparison)
- [ ] introduce doobie-tsql as a supported alpha
